import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Text from "@/components/Text";
import { motion } from "framer-motion";
function Philosophy() {
    const stats = [
        { num: "140", suffix: "+", desc: "Brands Launched" },
        { num: "28", suffix: "+", desc: "Countries Reached" },
        { num: "96", suffix: "%", desc: "Client Retention" },
    ];
    return (_jsxs(motion.section, { id: "philosophy", className: "bg-white grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-24 items-center px-6 md:px-16 py-16 md:py-28 h-screen", initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-100px" }, transition: { duration: 0.6 }, children: [_jsxs(motion.div, { initial: { opacity: 0, x: -30 }, whileInView: { opacity: 1, x: 0 }, viewport: { once: true, margin: "-100px" }, transition: { duration: 0.6 }, children: [_jsx(Text, { as: "p", font: "sans", size: "xs", weight: "medium", tracking: "custom-0_3em", uppercase: true, color: "accent", className: "mb-4", children: "Our Philosophy" }), _jsxs(Text, { as: "h2", font: "serif", size: "3xl", weight: "light", leading: "tight", tracking: "wide", color: "ink", className: "sm:text-4xl md:text-5xl lg:text-5xl", children: ["Beauty is not a luxury. ", _jsx("br", {}), " It is a", " ", _jsx(Text, { as: "em", italic: true, color: "accent", children: "Strategy" })] })] }), _jsxs(motion.div, { initial: { opacity: 0, x: 30 }, whileInView: { opacity: 1, x: 0 }, viewport: { once: true, margin: "-100px" }, transition: { duration: 0.6, delay: 0.2 }, children: [_jsx(Text, { as: "p", size: "sm", weight: "normal", leading: "loose", color: "muted", className: "md:text-base mb-8", children: "Every brand we touch is built on the belief that aesthetics and performance are not opposites \u2014 they are the same thing, viewed from different angles. We work with founders, CMOs, and creative directors who understand that perception is reality." }), _jsx(Text, { as: "p", size: "sm", weight: "normal", leading: "loose", color: "muted", className: "md:text-base mb-8", children: "Our process is rigorous. Our results are unmistakable. We do not make pretty things. We make things that convert, that resonate, that endure." }), _jsx(motion.div, { className: "grid grid-cols-3 gap-4 md:gap-8 pt-8 border-t border-warm", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-100px" }, transition: { duration: 0.6, delay: 0.4 }, children: stats.map((stat, i) => (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-100px" }, transition: { duration: 0.4, delay: 0.5 + i * 0.1 }, children: [_jsxs(Text, { as: "div", font: "serif", size: "2xl", weight: "light", color: "ink", className: "sm:text-3xl md:text-4xl lg:text-5xl mb-1", children: [stat.num, _jsx("sup", { className: "text-base md:text-lg", children: stat.suffix })] }), _jsx(Text, { as: "div", size: "custom-0_65rem", tracking: "widest", uppercase: true, color: "muted", className: "md:text-xs", children: stat.desc })] }, i))) })] })] }));
}
export default Philosophy;
